import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Customer from "@/components/Customer";
import Glance from "@/components/Glance";
import Testimonial from "@/components/Testimonial";
import Guaranteed from "@/components/Guaranteed";
import InfoTour from "@/components/InfoTour";
import Sponsors from "@/components/Sponsors";
import Contact from "@/components/Contact";
import Plan from "@/components/Plan";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-white">
        <Plan />
        <Customer />
        <Glance />
        <Testimonial />
        <Guaranteed />
        <InfoTour />
        <Sponsors />
        <Contact />
      </div>
    </>
  );
}
